services:
  zentra-shipping-service-redis-node-1:
    container_name: zentra-shipping-service-redis-node-1
    image: redis:7.2.2
    ports:
      - 5381:6379
      - 15381:16379
    volumes:
      - type: bind
        source: ./doc/database/redis/redis-node-1.conf
        target: /usr/local/etc/redis/redis.conf
      - type: volume
        source: zentra-shipping-service-redis-data-node-1
        target: /data
    networks:
      zentra-shipping-service-redis-network:
        ipv4_address: 182.48.0.11
      zentra-shipping-service-network:
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    restart: on-failure
  zentra-shipping-service-redis-node-2:
    container_name: zentra-shipping-service-redis-node-2
    image: redis:7.2.2
    ports:
      - 5382:6379
      - 15382:16379
    volumes:
      - type: bind
        source: ./doc/database/redis/redis-node-2.conf
        target: /usr/local/etc/redis/redis.conf
      - type: volume
        source: zentra-shipping-service-redis-data-node-2
        target: /data
    networks:
      zentra-shipping-service-redis-network:
        ipv4_address: 182.48.0.12
      zentra-shipping-service-network:
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    restart: on-failure

  zentra-shipping-service-redis-node-3:
    container_name: zentra-shipping-service-redis-node-3
    image: redis:7.2.2
    ports:
      - 5383:6379
      - 15383:16379
    volumes:
      - type: bind
        source: ./doc/database/redis/redis-node-3.conf
        target: /usr/local/etc/redis/redis.conf
      - type: volume
        source: zentra-shipping-service-redis-data-node-3
        target: /data
    networks:
      zentra-shipping-service-redis-network:
        ipv4_address: 182.48.0.13
      zentra-shipping-service-network:
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    restart: on-failure

  zentra-shipping-service-redis-node-4:
    container_name: zentra-shipping-service-redis-node-4
    image: redis:7.2.2
    ports:
      - 5384:6379
      - 15384:16379
    volumes:
      - type: bind
        source: ./doc/database/redis/redis-node-4.conf
        target: /usr/local/etc/redis/redis.conf
      - type: volume
        source: zentra-shipping-service-redis-data-node-4
        target: /data
    networks:
      zentra-shipping-service-redis-network:
        ipv4_address: 182.48.0.14
      zentra-shipping-service-network:
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    restart: on-failure

  zentra-shipping-service-redis-node-5:
    container_name: zentra-shipping-service-redis-node-5
    image: redis:7.2.2
    ports:
      - 5385:6379
      - 15385:16379
    volumes:
      - type: bind
        source: ./doc/database/redis/redis-node-5.conf
        target: /usr/local/etc/redis/redis.conf
      - type: volume
        source: zentra-shipping-service-redis-data-node-5
        target: /data
    networks:
      zentra-shipping-service-redis-network:
        ipv4_address: 182.48.0.15
      zentra-shipping-service-network:
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    restart: on-failure

  zentra-shipping-service-redis-node-6:
    container_name: zentra-shipping-service-redis-node-6
    image: redis:7.2.2
    ports:
      - 5386:6379
      - 15386:16379
    volumes:
      - type: bind
        source: ./doc/database/redis/redis-node-6.conf
        target: /usr/local/etc/redis/redis.conf
      - type: volume
        source: zentra-shipping-service-redis-data-node-6
        target: /data
    networks:
      zentra-shipping-service-redis-network:
        ipv4_address: 182.48.0.16
      zentra-shipping-service-network:
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    restart: on-failure

  zentra-shipping-service-redisinsight:
    container_name: zentra-shipping-service-redisinsight
    image: redislabs/redisinsight:2.50
    ports:
      - 5546:5540
    networks:
      - zentra-shipping-service-redis-network

volumes:
  zentra-shipping-service-redis-data-node-1:
    name: zentra-shipping-service-redis-data-node-1
  zentra-shipping-service-redis-data-node-2:
    name: zentra-shipping-service-redis-data-node-2
  zentra-shipping-service-redis-data-node-3:
    name: zentra-shipping-service-redis-data-node-3
  zentra-shipping-service-redis-data-node-4:
    name: zentra-shipping-service-redis-data-node-4
  zentra-shipping-service-redis-data-node-5:
    name: zentra-shipping-service-redis-data-node-5
  zentra-shipping-service-redis-data-node-6:
    name: zentra-shipping-service-redis-data-node-6

networks:
  zentra-shipping-service-network:
    name: zentra-shipping-service-network
    driver: bridge
  zentra-shipping-service-redis-network:
    name: zentra-shipping-service-redis-network
    driver: bridge
    ipam:
      config:
        - subnet: 182.48.0.0/16
  zentra-network:
    name: zentra-network
    external: true
